python genetic_algorithm_tsp.py "duo_files/AISearchfile012.txt" "tours/genetic/mutations/swap-mutation,mutation-rate-0.035,init-pop-200/tourAISearchfile012.txt"
python genetic_algorithm_tsp.py "duo_files/AISearchfile017.txt" "tours/genetic/mutations/swap-mutation,mutation-rate-0.035,init-pop-200/tourAISearchfile017.txt"
python genetic_algorithm_tsp.py "duo_files/AISearchfile021.txt" "tours/genetic/mutations/swap-mutation,mutation-rate-0.035,init-pop-200/tourAISearchfile021.txt"
python genetic_algorithm_tsp.py "duo_files/AISearchfile026.txt" "tours/genetic/mutations/swap-mutation,mutation-rate-0.035,init-pop-200/tourAISearchfile026.txt"
python genetic_algorithm_tsp.py "duo_files/AISearchfile042.txt" "tours/genetic/mutations/swap-mutation,mutation-rate-0.035,init-pop-200/tourAISearchfile042.txt"
python genetic_algorithm_tsp.py "duo_files/AISearchfile048.txt" "tours/genetic/mutations/swap-mutation,mutation-rate-0.035,init-pop-200/tourAISearchfile048.txt"
python genetic_algorithm_tsp.py "duo_files/AISearchfile058.txt" "tours/genetic/mutations/swap-mutation,mutation-rate-0.035,init-pop-200/tourAISearchfile058.txt"
python genetic_algorithm_tsp.py "duo_files/AISearchfile175.txt" "tours/genetic/mutations/swap-mutation,mutation-rate-0.035,init-pop-200/tourAISearchfile175.txt"
python genetic_algorithm_tsp.py "duo_files/AISearchfile180.txt" "tours/genetic/mutations/swap-mutation,mutation-rate-0.035,init-pop-200/tourAISearchfile180.txt"
python genetic_algorithm_tsp.py "duo_files/AISearchfile535.txt" "tours/genetic/mutations/swap-mutation,mutation-rate-0.035,init-pop-200/tourAISearchfile535.txt"

:: python genetic_algorithm_tsp_heavy.py "duo_files/AISearchfile012.txt" "tours/genetic/mutations/swap-mutation,mutation-rate-0.3,heavy/tourAISearchfile012.txt"
:: python genetic_algorithm_tsp_heavy.py "duo_files/AISearchfile017.txt" "tours/genetic/mutations/swap-mutation,mutation-rate-0.3,heavy/tourAISearchfile017.txt"
:: python genetic_algorithm_tsp_heavy.py "duo_files/AISearchfile021.txt" "tours/genetic/mutations/swap-mutation,mutation-rate-0.3,heavy/tourAISearchfile021.txt"
:: python genetic_algorithm_tsp_heavy.py "duo_files/AISearchfile026.txt" "tours/genetic/mutations/swap-mutation,mutation-rate-0.3,heavy/tourAISearchfile026.txt"
:: python genetic_algorithm_tsp_heavy.py "duo_files/AISearchfile042.txt" "tours/genetic/mutations/swap-mutation,mutation-rate-0.3,heavy/tourAISearchfile042.txt"
:: python genetic_algorithm_tsp_heavy.py "duo_files/AISearchfile048.txt" "tours/genetic/mutations/swap-mutation,mutation-rate-0.3,heavy/tourAISearchfile048.txt"
:: python genetic_algorithm_tsp_heavy.py "duo_files/AISearchfile058.txt" "tours/genetic/mutations/swap-mutation,mutation-rate-0.3,heavy/tourAISearchfile058.txt"
:: python genetic_algorithm_tsp_heavy.py "duo_files/AISearchfile175.txt" "tours/genetic/mutations/swap-mutation,mutation-rate-0.3,heavy/tourAISearchfile175.txt"
:: python genetic_algorithm_tsp_heavy.py "duo_files/AISearchfile180.txt" "tours/genetic/mutations/swap-mutation,mutation-rate-0.3,heavy/tourAISearchfile180.txt"
:: python genetic_algorithm_tsp_heavy.py "duo_files/AISearchfile535.txt" "tours/genetic/mutations/swap-mutation,mutation-rate-0.3,heavy/tourAISearchfile535.txt"
